//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CalificacionRappitendero
    {
        public int id_califrappiden { get; set; }
        public string calificacion { get; set; }
        public string descripcion { get; set; }
        public int id_rappitendero { get; set; }
    
        public virtual Rappitendero Rappitendero { get; set; }
    }
}
