//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CuentaEmpresa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CuentaEmpresa()
        {
            this.Empresa = new HashSet<Empresa>();
        }
    
        public int id_titular { get; set; }
        public string nom_titular { get; set; }
        public string tipo_documento { get; set; }
        public string tipo_cuenta { get; set; }
        public string num_cuenta { get; set; }
        public string num_interban { get; set; }
        public string domi_fiscal { get; set; }
        public Nullable<int> num_titular { get; set; }
        public string correo_titular { get; set; }
        public int id_país { get; set; }
        public int id_entidad { get; set; }
    
        public virtual Entidad_Financiera Entidad_Financiera { get; set; }
        public virtual Pais Pais { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Empresa> Empresa { get; set; }
    }
}
