//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detalle_Pedido
    {
        public int id_detalle_pedido { get; set; }
        public int id_producto { get; set; }
        public int id_pedido { get; set; }
        public Nullable<int> cantidad { get; set; }
        public Nullable<double> subtotal_productos { get; set; }
        public string extras { get; set; }
        public string direccion_entrega { get; set; }
        public Nullable<double> Total { get; set; }
    
        public virtual Pedido Pedido { get; set; }
        public virtual Producto Producto { get; set; }
        public virtual Resumen_Pago Resumen_Pago { get; set; }
    }
}
