//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empresa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Empresa()
        {
            this.Categoría = new HashSet<Categoría>();
            this.Sucursal = new HashSet<Sucursal>();
        }
    
        public int id_empresa { get; set; }
        public int id_usuario { get; set; }
        public int id_rubro { get; set; }
        public int id_titular { get; set; }
        public string nom_tienda { get; set; }
        public string modelo_tienda { get; set; }
        public string tipo_persona { get; set; }
        public string num_ruc { get; set; }
        public string num_cuenta { get; set; }
        public string razon_social { get; set; }
        public string codigo_referido { get; set; }
        public string estado_empresa { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Categoría> Categoría { get; set; }
        public virtual CuentaEmpresa CuentaEmpresa { get; set; }
        public virtual Rubro Rubro { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual Representante_legal Representante_legal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sucursal> Sucursal { get; set; }
    }
}
