//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EntregaProducto
    {
        public int id_entrega { get; set; }
        public int id_rappitendero { get; set; }
        public int id_pedido { get; set; }
        public System.DateTime tiempo { get; set; }
        public string distancia_total { get; set; }
        public string descrip_recoger { get; set; }
        public string descrip_entrega { get; set; }
        public string descrip_producto { get; set; }
        public double cantid_producto { get; set; }
        public double ganancia_total { get; set; }
    
        public virtual Pedido Pedido { get; set; }
        public virtual Rappitendero Rappitendero { get; set; }
    }
}
