//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class facturacion
    {
        public int id_facturacion { get; set; }
        public int id_pedido { get; set; }
        public string nombre_usuario { get; set; }
        public string descrip_pedido { get; set; }
        public string direccion_pedido { get; set; }
        public System.DateTime tiempo_pedido { get; set; }
        public double costo_producto { get; set; }
        public string entrega_domicilo { get; set; }
        public double propina { get; set; }
        public double Total_Pago { get; set; }
    
        public virtual Pedido Pedido { get; set; }
    }
}
