//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class bdrappiEntities2 : DbContext
    {
        public bdrappiEntities2()
            : base("name=bdrappiEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CalificacionRappitendero> CalificacionRappitendero { get; set; }
        public virtual DbSet<Categoría> Categoría { get; set; }
        public virtual DbSet<Ciudad> Ciudad { get; set; }
        public virtual DbSet<Cliente> Cliente { get; set; }
        public virtual DbSet<CuentaEmpresa> CuentaEmpresa { get; set; }
        public virtual DbSet<Cupón_descuento> Cupón_descuento { get; set; }
        public virtual DbSet<Detalle_Pedido> Detalle_Pedido { get; set; }
        public virtual DbSet<Distrito> Distrito { get; set; }
        public virtual DbSet<Empresa> Empresa { get; set; }
        public virtual DbSet<Entidad_Financiera> Entidad_Financiera { get; set; }
        public virtual DbSet<EntregaProducto> EntregaProducto { get; set; }
        public virtual DbSet<facturacion> facturacion { get; set; }
        public virtual DbSet<ListaPago> ListaPago { get; set; }
        public virtual DbSet<Método_Pago> Método_Pago { get; set; }
        public virtual DbSet<N_Tarjeta_Pago> N_Tarjeta_Pago { get; set; }
        public virtual DbSet<Pais> Pais { get; set; }
        public virtual DbSet<Pedido> Pedido { get; set; }
        public virtual DbSet<Producto> Producto { get; set; }
        public virtual DbSet<Rappitendero> Rappitendero { get; set; }
        public virtual DbSet<Representante_legal> Representante_legal { get; set; }
        public virtual DbSet<Resumen_Pago> Resumen_Pago { get; set; }
        public virtual DbSet<Rubro> Rubro { get; set; }
        public virtual DbSet<Sucursal> Sucursal { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TiempEntregaProd> TiempEntregaProd { get; set; }
        public virtual DbSet<TomaPedido> TomaPedido { get; set; }
        public virtual DbSet<toppings> toppings { get; set; }
        public virtual DbSet<Transporte> Transporte { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
        public virtual DbSet<RegistrarTarjeta> RegistrarTarjeta { get; set; }
        public virtual DbSet<PagoRappitendero> PagoRappitendero { get; set; }
    }
}
