//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegistrarTarjeta
    {
        public int id_rTarjeta { get; set; }
        public string n_tarjeta { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        public string fecha_tarjeta { get; set; }
        public string cvv { get; set; }
    }
}
