//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Representante_legal
    {
        public int id_rep { get; set; }
        public string nom_rep { get; set; }
        public string ape_rep { get; set; }
        public string tipo_rep { get; set; }
        public string num_rep { get; set; }
        public int id_empresa { get; set; }
    
        public virtual Empresa Empresa { get; set; }
    }
}
