//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Resumen_Pago
    {
        public int id_rpago { get; set; }
        public int id_detalle_pedido { get; set; }
        public string total_productos { get; set; }
        public string tarifa_servicio { get; set; }
        public int id_cupon { get; set; }
        public string Propina { get; set; }
        public string costo_producto { get; set; }
        public string total_cobrar { get; set; }
    
        public virtual Cupón_descuento Cupón_descuento { get; set; }
        public virtual Detalle_Pedido Detalle_Pedido { get; set; }
    }
}
