//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sucursal
    {
        public int id_sucursal { get; set; }
        public string direccion_sucursal { get; set; }
        public int id_empresa { get; set; }
    
        public virtual Empresa Empresa { get; set; }
        public virtual Pedido Pedido { get; set; }
    }
}
