//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TiempEntregaProd
    {
        public int id_tiempEntrega { get; set; }
        public int id_pedido { get; set; }
        public string direccion_entrega { get; set; }
        public string entrega_estimada { get; set; }
    
        public virtual Pedido Pedido { get; set; }
    }
}
