//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transporte
    {
        public int id_transporte { get; set; }
        public int id_rappitendero { get; set; }
        public Nullable<int> tipo_transporte { get; set; }
        public byte[] foto_licenciadel { get; set; }
        public byte[] foto_licenciatra { get; set; }
        public string fecha_venc_lic { get; set; }
        public byte[] foto_soadel { get; set; }
        public byte[] foto_soaad { get; set; }
        public string fec_venc_soa { get; set; }
        public string num_placa { get; set; }
    
        public virtual Rappitendero Rappitendero { get; set; }
    }
}
