//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usuario()
        {
            this.Empresa = new HashSet<Empresa>();
            this.Rappitendero = new HashSet<Rappitendero>();
        }
    
        public int id_usuario { get; set; }
        public string nom_usuario { get; set; }
        public string ape_usuario { get; set; }
        public string correo_usuario { get; set; }
        public string clave_usuario { get; set; }
        public string celular_usuario { get; set; }
        public string T_documento { get; set; }
        public string N_documento { get; set; }
        public string fechnac { get; set; }
        public string sexo { get; set; }
        public int id_pais { get; set; }
        public string direccion_usuario { get; set; }
        public string foto_usuario { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Empresa> Empresa { get; set; }
        public virtual Pais Pais { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rappitendero> Rappitendero { get; set; }
    }
}
